version: '3'
services:
    api:
        container_name: api
        hostname: api
        build:
            context: ../
            dockerfile: deployments/go.Dockerfile
        ports:
            - "8083:8083"
        environment:
          API_PORT: 8083
        env_file:
            - app.env
        command: "go run cmd/api/main.go"
        networks:
            - internal_net
        depends_on:
            - worker
            - redis_db
        restart: unless-stopped

    worker:
        hostname: worker
        build:
            context: ../
            dockerfile: deployments/go.Dockerfile
        env_file:
            - app.env
        command: "go run cmd/worker/main.go"
        networks:
            - internal_net
        depends_on:
            - redis_db
        restart: unless-stopped

    redis_db:
        image: 'redis:4-alpine'
        container_name: redis_db
        command: redis-server --requirepass secret
        expose:
            - 6379
        networks:
            - internal_net
        restart: unless-stopped

networks:
    internal_net:
