language: node_js

cache:
  yarn: true

stages:
  - lint
  - test
  - docker

jobs:
  include:

    - stage: lint
      script:
        - yarn run lint

    - stage: test
      script:
        - yarn run test

    - stage: docker
      sudo: required
      services:
        - docker
      script:
        - docker build -t felippemauricio/challenge-bravo .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push felippemauricio/challenge-bravo
        - docker tag felippemauricio/challenge-bravo felippemauricio/challenge-bravo:$TRAVIS_COMMIT
        - docker push felippemauricio/challenge-bravo:$TRAVIS_COMMIT
      on:
        branch: master
