version: '3.2'
services:
  redis:
    image: redis
  web:
    build: ./currency_converter
    image: currency_converter
    expose:
      - "8000"
    links:
      - redis
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    links:
     - web