version: '3.1'
services:
  db:
    container_name: db_bravro
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'bravo'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-P", "3307" ]
      timeout: 20s
      retries: 10
  server:
    container_name: api_bravro
    image: openjdk:8
    ports:
      - 8081:8080
    links:
      - db
    volumes:
      - ./build/libs:/jar
    command: java -jar /jar/bravo.jar
    depends_on:
      db:
        condition: service_healthy


