version: "3"
services:
  redis:
    image: redis
    container_name: cache
    expose:
    - 6379
  exchange-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "6660:6660"
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache