version: "3.5"

services:
    hurb:
        image: node:14
        command: bash -c "yarn dev"
        working_dir: /home/node/app
        volumes:
            - ./backend:/home/node/app
        ports:
            - "5000:5000"
        depends_on:
            - mongo
            - redis
        links:
            - mongo
            - redis

    mongo:
        image: mongo:4.2.0
        ports:
            - 27017:27017

    redis:
        image: redis
        ports:
            - 6379:6379
