version: '3'

services:
  redis:
    container_name: currency-converter-redis
    image: redis:5.0
    restart: 'unless-stopped'
    tty: true
    ports:
      - 6379:6379
    command: redis-server --requirepass BxhrNK6pzW2Ytojd
    volumes:
      - currency-converter-redis-volume:/data
    networks:
    - currency-converter-network

  php:
    container_name: currency-converter-php
    image: php:7.2.17-fpm
    restart: 'unless-stopped'
    working_dir: /src
    ports:
      - 9000:9000
    volumes:
      - ./src:/src
    env_file:
      - ./src/.env
    depends_on:
      - redis
    networks:
      - currency-converter-network

  nginx:
    container_name: currency-converter-nginx
    image: nginx:1.15.12
    restart: 'unless-stopped'
    tty: true
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/src
    depends_on:
      - php
    networks:
      - currency-converter-network

volumes:
  currency-converter-redis-volume:

networks:
  currency-converter-network:
    driver: bridge