version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'bravo'
      POSTGRES_USER: 'bravo'
      POSTGRES_PASSWORD: '3R@v0'
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - bravo

  api:
    build: .
    ports:
     - 80:80
    volumes:
      - .:/home/application
    networks: 
      - bravo
    depends_on:
      - postgres

volumes:
  postgres:
networks: 
  bravo: