version: '2'

services:
  pythonapi:
    restart: always
    hostname: python_api
    build: ./src/api/python/.
    expose:
      - "8888"
    ports:
      - "8888:8888"
    command: ["/usr/local/bin/gunicorn", "-w", "8", "-b", ":8888", "converter:app"]
    depends_on:
      - redis
      - worker

  goapi:
    build: ./src/api/golang/.
    hostname: go_api
    restart: always
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - worker

  worker:
    restart: always
    hostname: worker
    build: ./src/worker/.
    depends_on:
      - redis

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    restart: always

  nginx:
    image: nginx
    restart: always
    hostname: nginx
    depends_on:
      - goapi
      - pythonapi
    ports:
      - "3333:3333"
    volumes:
      - "./confs/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./scripts:/scripts"
  
  tester:
    restart: "no"
    build: ./src/tester/.
    volumes:
      - "./src/tester/scripts:/scripts"