version: "2"
services:
    api:
        build:
            context: ./
            dockerfile: docker/api/api.dockerfile
            args:
                - HOST_UID=${UID}
        working_dir: /usr/src/app
        volumes:
            - "./app:/usr/src/app"
        ports:
            - "3000:3000"
        links:
            - redis
    redis:
        container_name: bravo-redis
        image: "redis:4.0.11"
        ports:
            - "6379:6379"
        volumes:
            - ./data:/data
