version: "3.2"

services:
  challenge-bravo:
    build: ./
    restart: always
    ports:
      - "8082:8082"
    networks:
      back:
        aliases:
          - "challenge-bravo.service.com.br"
networks:
  back: