version: "3"

services:

  nginx:
    image: nginx:latest
    container_name: cbravo_nginx
    ports:
      - 80:80
    expose:
      - 80
    volumes:
      - ./:/usr/share/nginx/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/logs:/var/log/nginx

  php-fpm:
    image: php:7.2.10-fpm
    container_name: cbravo_nginx_php
    build:
      context: docker/php-fpm
    volumes:
      - ./:/usr/share/nginx/html
      - ./docker/php-fpm/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php-fpm/logs:/usr/local/var/log
    external_links:
      - nginx:cbravo.local
    environment:
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G


