version: '2'

services:
  api:
    restart: always
    hostname: api
    build: ./src/api/.
    expose:
      - "8888"
    ports:
      - "8888:8888"
    command: ["/usr/local/bin/gunicorn", "-w", "8", "-b", ":8888", "converter:app"]
    depends_on:
      - redis
      - worker
  worker:
    restart: always
    hostname: worker
    build: ./src/worker/.
    command: ["/usr/local/bin/gunicorn", "-w", "1", "-b", ":5555", "worker:app"]
    depends_on:
      - redis
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    restart: always
  nginx:
    image: nginx
    restart: always
    hostname: nginx
    depends_on:
      - api
    ports:
      - "3333:80"
    volumes:
      - "./confs/nginx/default.conf:/etc/nginx/conf.d/default.conf"