version: "3"
networks:
  cache:
services:
  redis:
    image: redis
    container_name: cache
    networks: 
      - cache
  worker:
    build: ./worker
    container_name: worker
    env_file: .env_worker
    depends_on:
      - redis
    links:
      - redis
    networks:
      - cache
  api:
    build: ./api
    container_name: api
    depends_on:
      - redis
      - worker
    links:
      - redis
    networks:
      - cache
    environment:
      - PORT=3000
      - REDIS_HOST=redis://cache
    ports:
      - "3000:80"
