version: "3.3"

services:
  mongo-currency:
    container_name: mongo-currency
    image: "mongo:3.4-jessie"
    ports:
      - "27017:27017"
    volumes:
      - ./offline-data/mongodb:/data/db
  api:
    container_name: api
    command: npm run dev
    build:
      context: .
    volumes:
      - .:/api
      - node-modules-api:/api/node_modules
    links:
      - mongo-currency:mongo-currency
    expose:
      - 80
    ports:
      - 3000:80
      - 9229:9229
    environment:
      PORT: 80
      HOST: 0.0.0.0
      MONGODB_ENDPOINT: "mongodb://mongo-currency:27017/currencies"
volumes:
  node-modules-api:
