version: '3.4'

services:
  db:
    image: mysql:8
    container_name: carv_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: Currency
      MYSQL_ROOT_PASSWORD: Hurb2020!
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - '3306:3306'

  cache:
    image: redis
    container_name: carvr_redis
    command: redis-server
    ports:
      - "6379:6379"

  currencyconverter.api:
    image: ${DOCKER_REGISTRY-}currencyconverterapi
    container_name: carv_CurrencyConverter
    links:
      - db
      - cache
    build:
      context: .
      dockerfile: CurrencyConverter.API/Dockerfile
    expose:
      - '8090'
    ports:
      - '8090:80'
    depends_on:
      - db
      - cache