version: '3'
services:
    redis:
        container_name: cache
        image: redis
        ports:
            - '6379:6379'
    app:
        build:
            context: ./
            args:
                USER_ID: $USER_ID
                ENV: development
        volumes:
            - ./:/var/www/hurb
        ports:
            - 3000:3000
        links:
            - redis
        environment:
            - REDIS_URL=redis://cache
