version: "3"
networks:
  cache:
services:
  redis:
    image: redis
    container_name: cache
    networks: 
      - cache
  worker:
    build: ./worker
    container_name: worker
    env_file: .env_worker
    depends_on:
      - redis
    links:
      - redis
    networks:
      - cache
