version: '3.4'

services:
  challenge-bravo:
    image: challenge-bravo
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js