version: '3'
services:
    challenge-bravo:
        container_name: coin-converter
        build: .
        command: bash -c "uvicorn challenge_bravo.main:app --host 0.0.0.0 --port 8000"
        ports:
            - 80:8000
        env_file:
            - .env
        volumes:
            - .:/app
        networks:
            - coin-network
        depends_on:
            - database

    database:
        container_name: database
        image: postgres
        environment:
            - POSTGRES_DB=coin_converter
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - coin-network

volumes:
    pgdata:

networks:
    coin-network:
        driver: bridge
