version: "3"
networks:
  cache:
services:
  redis:
    image: redis
    container_name: cache
    networks: 
      - cache
    ports:
      - "6379:6379"
  worker:
    build: ./worker
    container_name: worker
    env_file: .env_worker
    depends_on:
      - redis
    links:
      - redis
    networks:
      - cache
  api:
    build: ./api
    container_name: api
    env_file: .env_api
    depends_on:
      - redis
      - worker
    links:
      - redis
    networks:
      - cache
    ports:
      - "3000:3000"
