version: '3'
services:
  db:
    image: redis:6.0.6-alpine
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
  web:
    build: .
    environment:
      - FLASK_APP=api/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/var/www/currency-api
    depends_on:
      - db
