version: '3'

services:
  hurby:
    build: .
    image: antoniojr78/challenge-bravo:Hurby-1.0
    container_name: hurby
    environment:
      - FLASK_ENV=production
    ports:
      - 5000:5000
    depends_on:
    - redis
  redis:
    image: redis
    container_name: db_cache
    command: redis-server --requirepass Ch4ll5ngeBr@vo
