version: '3'

services:
    redis:
        image: redis:6-alpine
        container_name: bravo-challenge-cache
        ports:
            - 6380:6379
        networks:
            - bravochallenge-network

    node:
        depends_on:
            - redis
        build:
            context: .
            dockerfile: Dockerfile
        image: hurb/bravo-challenge
        tty: true
        container_name: bravo-challenge-api
        environment:
            - NODE_ENV=production
            - HOST=0.0.0.0
            - PORT=8080
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        ports:
            - 8090:8080
        links:
            - redis
        networks:
            - bravochallenge-network

networks:
    bravochallenge-network:
        driver: bridge
