version: "3"
networks:
  cache:
services:
  redis:
    image: redis
    container_name: cache
    networks: 
      - cache
  worker:
    build: ./worker
    container_name: worker
    env_file: .env
    depends_on:
      - redis
    links:
      - redis
    networks:
      - cache
    environment:
      - REDIS_HOST=redis://cache
  api:
    hostname: api
    container_name: api
    build: 
      context: ./api
      args:
        - appname=api
    depends_on:
      - redis
      - worker
    links:
      - redis
    networks:
      - cache
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_HOST=redis://cache
  nginx:
      image: nginx
      hostname: nginx
      depends_on:
        - api
        - worker
      ports:
        - "4000:4000"
      volumes:
        - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      networks:
      - cache