version: '3'
services:
  db:
    image: redis:6.0.6-alpine
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
  web:
    build: .
    command: gunicorn --workers=3 --threads=3 --bind 0.0.0.0:5000 wsgi:app
    environment:
      - FLASK_APP=api/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/var/www/currency-api
    depends_on:
      - db
  nginx:
    build: ./services/nginx
    ports:
      - "8000:80"
    depends_on:
      - web
