version: '3'
services:
    redis:
        container_name: cache
        image: redis
        ports:
            - '6379:6379'
    app:
        build: ./
        ports:
            - 3000:3000
        links:
            - redis
        environment:
            - REDIS_URL=redis://cache
