version: '3'

services:
  app:
    container_name: 'node-bravo'
    build: .
    volumes:
      - '.:/usr/app'
    command: 'yarn dev'
    ports:
      - '3333:3333'
    depends_on:
      - 'mongo'
      - 'redis'
  mongo:
    container_name: 'mongo-bravo'
    image: 'mongo'
    ports:
      - '27017:27017'
  redis:
    container_name: 'redis-bravo'
    image: 'redis'
    ports:
      - '6379:6379'