version: '3'
services:
  db:
    image: redis:6.0.6
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
  web:
    build: .
    command: gunicorn --workers=7 --bind 0.0.0.0:5000 wsgi:app
    environment:
      - FLASK_APP=api/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/var/www/currency-api
    depends_on:
      - db
  nginx:
    build: ./services/nginx
    command: nginx
    ports:
      - "80:80"
    depends_on:
      - web
  performance:
    build:  ./services/performance
    command:  ab -r -n 10000 -c 100 'http://web:5000/convert/?from=USD&to=BRL&amount=10'
    depends_on:
      - web
