version: "3"
services:
  app:
    image: golang:1.10
    build: .
    volumes:
      - "./:/go/src/${PROJECT_NAME}"
    ports:
      - "${HOST_PORT}:8080"
    working_dir: /go/src/${PROJECT_NAME}/
    command: ['bash', '-c', 'echo -e "\\033[35m\nDownloading project dependencies...\n"; wget -O /usr/bin/dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64; chmod +x /usr/bin/dep; dep ensure -vendor-only -v; go get -v github.com/taoza/fresh; echo -e "\\033[35m\nDownload done. \\033[35m\nRunning ${PROJECT_NAME}...\n"; fresh -- -d;']