version: "3.8"
services:
  bravo_api:
    build: 
      context: .
      dockerfile: Dockerfile.development
    depends_on: 
      - mongodb
    restart: always
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data
    ports:
      - '27017:27017'

volumes:
    mongo-data: