version: "3.8"
services:
  bravo_api:
    image: node:14.15.1-alpine
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: volume
        source: nodemodules
        target: /app/node_modules
        volume:
          nocopy: true
    depends_on: 
      - mongodb
    working_dir: /app
    command: npm run dev
    ports:
      - "3030:3030"

  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data
    ports:
      - '27017:27017'

volumes:
    nodemodules:
    mongo-data: