version: "3.8"
services:
  bravo_api:
    build: 
      context: .
      dockerfile: Dockerfile.development
    depends_on: 
      - mongo
    restart: always
    ports:
      - 3030:3030
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data
    ports:
      - '27017:27017'
    command: mongod --quiet --logpath /dev/null

  redis:
    image: "redis"
    ports:
      - "6379:6379"

volumes:
    mongo-data: