[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  branch = "master"
  name = "github.com/mediocregopher/radix.v2"

[prune]
  go-tests = true
  unused-packages = true
