name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: ['1.12', '1.13', '1.14']
    name: Go ${{ matrix.go }} testing
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Running lint
        run: make lint
      - name: Running test
        run: make lint

  build:
    runs-on: ubuntu-16.04
    name: Build on Go 1.13.x
    env:
      artifact_name: dist-${{ github.run_id }}-${{ github.sha }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - name: Build running
        run: make
